### ISSUE TITLE
line-sink-ditch error

### ISSUE THREAD

**Issue by PilbaraPanther** [mbakker7/ttim#14]
When running line-sink-ditch notebook an error occurs when executing the second cell
**NameError**: name 'LineSinkDitchString' is not defined

when adding linesink.LineSinkDitchString, this error occurs
 **AttributeError**: 'LineSinkDitchString' object has no attribute 'strengthinflayers' occurs

The error also occurs when using the element in my own models.

Using version ttim-0.4.0

**Comment by dbrakenhoff** [comment]
In the ttim-0.4.0 release the LineSinkDitchString element is not imported at module level. It's "hidden" in ttim.linesink:

```python
import ttim
ttim.linesink.LineSinkDitchString()
```

But I'm not sure that will make the notebook work, I still got an error after adding that to the notebook. Your best bet, I think, is to install TTim from the Github repository.

**Comment by PilbaraPanther** [comment]
I copied the files from the Github repository and that has fixed the problem
