### ISSUE TITLE
m1.disvec maybe is not right

### ISSUE THREAD

**Issue by qingsonger** [mbakker7/ttim#19]
from ttim import *
ml = ModelMaq(kaq = [2.0, 3.0], z = [3, 2, 1, 0], c = [1e100], Saq = [0.003, 0.0001], Sll = [0.001], tmin = 1e-3, tmax = 1e2, M = 20)
w1 = Well(ml, xw = 0, yw = 0, rw = 1e-5, tsandQ = [(0,1)], layers = 0)
ml.solve()
print(ml.disvec(1,0,1,layers=0))  #(array([[-0.15911903]]), array([[nan]]))
print(ml.disvec(0,1,1,layers=0))  #(array([[0.]]), array([[0.]]))
I think the absolute value should be the same in the two positions. Why the values are zero in the position (0,1)?

**Comment by mbakker7** [comment]
Thanks for the report and sorry it took so long to fix. 
Check out the new TTim. Lots of improvements (including this bug figx).
