### ISSUE TITLE
typo in well.py

### ISSUE THREAD

**Issue by FrankvdToorn** [mbakker7/ttim#3]
Line 191 in Well.py contains a typo. It should be:

`self.rc = np.atleast_1d(rc).astype('float')`

**Comment by mbakker7** [comment]
I think this is already fixed in master. What is the line without the typo?

**Comment by FrankvdToorn** [comment]
Line 191 originally stated: 
`self.rc = np.atleast_1d(rc).atype('float')`

And indeed, it is currently solved in master. 
Issue can be closed.
